// Generated by CoffeeScript 1.10.0
(function() {
  var messages, num;

  messages = db.messages.find({
    hasTag: null
  }, {
    tags: 1
  });

  num = 0;

  messages.forEach(function(message) {
    var hasTag, ref;
    num += 1;
    if (!(num % 10000)) {
      print("Scan num", num);
    }
    hasTag = ((ref = message.tags) != null ? ref.length : void 0) ? true : false;
    return db.messages.update({
      _id: message._id
    }, {
      $set: {
        hasTag: hasTag
      }
    });
  });

  print("Finish num", num);

}).call(this);
