// Generated by CoffeeScript 1.10.0
(function() {
  var email, emailAddress, mobile, phoneNumber;

  phoneNumber = '18621654252';

  emailAddress = 'yong@teambition.com';

  mobile = db.mobiles.findOne({
    phoneNumber: phoneNumber
  });

  email = db.emails.findOne({
    emailAddress: emailAddress
  });

  if (mobile != null ? mobile._id : void 0) {
    db.mobiles.remove({
      _id: mobile._id
    });
  }

  if (mobile != null ? mobile.user : void 0) {
    db.users.remove({
      _id: mobile.user
    });
  }

  if (email != null ? email._id : void 0) {
    db.emails.remove({
      _id: email._id
    });
  }

  if (email != null ? email.user : void 0) {
    db.users.remove({
      _id: email.user
    });
  }

}).call(this);
