if typeof window isnt 'undefined'
  require 'codemirror/addon/display/placeholder'
  require 'codemirror/mode/clike/clike'
  require 'codemirror/mode/clojure/clojure'
  require 'codemirror/mode/coffeescript/coffeescript'
  require 'codemirror/mode/commonlisp/commonlisp'
  require 'codemirror/mode/css/css'
  require 'codemirror/mode/go/go'
  require 'codemirror/mode/haskell/haskell'
  require 'codemirror/mode/htmlmixed/htmlmixed'
  require 'codemirror/mode/javascript/javascript'
  require 'codemirror/mode/markdown/markdown'
  require 'codemirror/mode/php/php'
  require 'codemirror/mode/python/python'
  require 'codemirror/mode/ruby/ruby'
  require 'codemirror/mode/sql/sql'
